name: CI

on: [push, workflow_dispatch]

jobs:
  # LINUX CLI J
  linux-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Update APT and install tools
        run: |
          sudo apt update && sudo apt install -y unzip curl

      - name: Download Ngrok
        run: curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip

      - name: Extract Ngrok
        run: unzip ngrok.zip

      - name: Make Ngrok executable
        run: chmod +x ngrok

      - name: Authenticate Ngrok
        run: ./ngrok authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start SSH server
        run: |
          sudo apt install -y openssh-server
          sudo service ssh start
          echo "runner:runner" | sudo chpasswd
          sudo usermod -aG sudo runner
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Start Ngrok tunnel for SSH
        run: ./ngrok tcp 22 --region=us-cal-1
